language: scala
scala:
- 2.11.12
- 2.12.11
- 2.13.1
jdk:
- openjdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_EVENT_TYPE" = "push" -a "$TRAVIS_REPO_SLUG" = "b-studios/scala-effekt" ]; then bash
  scripts/decrypt-keys.sh; fi
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.3.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.2.1
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- if [ "$TRAVIS_SCALA_VERSION" == "2.12.11" ]; then sbt docs/makeMicrosite ; fi
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_EVENT_TYPE" = "push" -a "$TRAVIS_REPO_SLUG" = "b-studios/scala-effekt" -a "$TRAVIS_SCALA_VERSION" == "2.12.11" ]; then bash scripts/publishMicrosite.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then echo "Not in master branch, skipping deploy and release"; fi
