name: scala-steward
on:
  push:
  schedule:
  - cron: '0 4 * * *'
jobs:
  scala-steward:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - if: ${{ !github.event.repository.fork }}
      uses: scala-steward-org/scala-steward-action@v2.9.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
